module.exports = grammar({
  name: "sus",

  rules: {
    source_file: ($) => repeat($._line),

    _line: ($) =>
      seq(
        choice($.generated_by, $._metadata, $._score_data, $.comment),
        $._eol
      ),

    generated_by: ($) => seq("This file was generated by ", token(/.*/)),

    comment: ($) => prec(-1, /[^#].*/),

    _metadata: ($) =>
      choice(
        $.meta_title,
        $.meta_subtitle,
        $.meta_artist,
        $.meta_designer,
        $.meta_genre,
        $.meta_waveoffset,
        $.meta_difficulty,
        $.meta_playlevel,
        $.meta_songid,
        $.meta_wave,
        $.meta_jacket,
        $.meta_background,
        $.meta_movie,
        $.meta_movieoffset,
        $.meta_basebpm,
        $.meta_request
      ),

    meta_title: ($) => seq("#TITLE ", $.string),
    meta_subtitle: ($) => seq("#SUBTITLE ", $.string),
    meta_artist: ($) => seq("#ARTIST ", $.string),
    meta_genre: ($) => seq("#GENRE ", $.string),
    meta_designer: ($) => seq("#DESIGNER ", $.string),
    meta_difficulty: ($) => seq("#DIFFICULTY ", choice($.number, $.string)),
    meta_playlevel: ($) => seq("#PLAYLEVEL ", token(/[0-9]+\+?/)),

    meta_songid: ($) => seq("#SONGID ", $.string),
    meta_wave: ($) => seq("#WAVE ", $.string),
    meta_waveoffset: ($) => seq("#WAVEOFFSET ", $.number),
    meta_jacket: ($) => seq("#JACKET ", $.string),
    meta_background: ($) => seq("#BACKGROUND ", $.string),
    meta_movie: ($) => seq("#MOVIE ", $.string),
    meta_movieoffset: ($) => seq("#MOVIEOFFSET ", $.number),
    meta_basebpm: ($) => seq("#BASEBPM ", $.number),
    meta_request: ($) => seq("#REQUEST ", prec.right($.string)),

    _score_data: ($) =>
      choice(
        $.data_measure_length,
        $.data_bpm_definition,
        $.data_bpm_change,
        $.data_attribute_definition,
        $.data_attribute_change,
        $.data_attribute_no,
        $.data_hispeed_definition,
        $.data_hispeed_change,
        $.data_hispeed_no,
        $.data_measurebs,
        $.data_measurehs,
        $._note_data
      ),

    data_measure_length: ($) =>
      seq($.header, $.measure_number, "02", ":", $.number),

    data_bpm_definition: ($) => seq($.header, "BPM", $.data_id, ":", $.number),
    data_bpm_change: ($) =>
      seq($.header, $.measure_number, "08", ":", $.split_section),

    data_attribute_definition: ($) =>
      seq(
        $.header,
        "ATR",
        $.data_id,
        ":",
        '"',
        repeat(choice($.data_attribute_pair, ",")),
        '"'
      ),
    data_attribute_change: ($) => seq($.header, "ATTRIBUTE ", $.data_id),
    data_attribute_no: ($) => seq($.header, "NOATTRIBUTE"),

    data_attribute_pair: ($) => seq(choice("rh", "h", "pr"), ":", $.number),

    data_hispeed_definition: ($) =>
      seq(
        $.header,
        "TIL",
        $.data_id,
        ":",
        '"',
        repeat(choice(",", $.data_hispeed_info)),
        '"'
      ),
    data_hispeed_change: ($) => seq($.header, "HISPEED ", $.data_id),
    data_hispeed_no: ($) => seq($.header, "NOSPEED"),

    data_hispeed_info: ($) =>
      seq(
        field("meas", $.integer),
        "'",
        field("tick", $.integer),
        ":",
        field("speed", $.number)
      ),

    data_measurebs: ($) => seq($.header, "MEASUREBS ", $.integer),
    data_measurehs: ($) => seq($.header, "MEASUREHS ", $.data_id),

    _note_data: ($) =>
      choice(
        $.note_tap,
        $.note_hold,
        $.note_slide_1,
        $.note_slide_2,
        $.note_directional
      ),

    note_tap: ($) =>
      seq(
        $.header,
        $.measure_number,
        alias("1", $.note_type),
        $.lane_index,
        ":",
        $.split_section
      ),
    note_hold: ($) =>
      seq(
        $.header,
        $.measure_number,
        alias("2", $.note_type),
        $.lane_index,
        $.note_channel,
        ":",
        $.split_section
      ),
    note_slide_1: ($) =>
      seq(
        $.header,
        $.measure_number,
        alias("3", $.note_type),
        $.lane_index,
        $.note_channel,
        ":",
        $.split_section
      ),
    note_slide_2: ($) =>
      seq(
        $.header,
        $.measure_number,
        alias("4", $.note_type),
        $.lane_index,
        $.note_channel,
        ":",
        $.split_section
      ),
    note_directional: ($) =>
      seq(
        $.header,
        $.measure_number,
        alias("5", $.note_type),
        $.lane_index,
        $.note_channel,
        ":",
        $.split_section
      ),

    string: ($) => token(/".*"/),
    integer: ($) => token(/-?[0-9]+/),
    float: ($) => token(/-?[0-9]+\.[0-9]+/),
    number: ($) => choice($.integer, $.float),

    measure_number: ($) => token(/[0-9]{3}/),
    data_id: ($) => token(/[0-9a-z]{2}/i),
    lane_index: ($) => token(/[0-9a-z]{1}/i),
    note_channel: ($) => token(/[0-9a-z]{1}/i),

    split_section: ($) => repeat1(choice($.split_null, $.split_value)),

    split_null: ($) => token("00"),
    split_value: ($) => token(/[0-9a-z]{2}/i),

    _eol: ($) => choice("\r\n", "\n", "\r"),

    header: ($) => "#",
  },
});
